apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  template:
    spec:
      initContainers:
      - name: init-config
        image: solsson/kafka:2.6.0-initutils-nonroot@sha256:cae9390de5380a4a1cd88976b37161ecf32fd70cde347a1db458b17ffa7743b8
      containers:
      - name: broker
        image: solsson/kafka:2.6.0-kafka-server-start@sha256:97623a66ed7a245af8e12947d99f723d983fbfc83cae4f60febc0526235e1548
        args:
        - /etc/kafka/server.properties.$(POD_NAME)
