apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pzoo
spec:
  template:
    spec:
      initContainers:
      - name: init-config
        image: solsson/kafka:2.6.0-initutils-nonroot@sha256:cae9390de5380a4a1cd88976b37161ecf32fd70cde347a1db458b17ffa7743b8
      containers:
      - name: zookeeper
        image: solsson/kafka:2.6.0-zookeeper-server-start@sha256:9406e3c810254dfb2fddac951756a3f44d1036a0c476ff49e8055c8d465f5083
        args:
        - /etc/kafka/zookeeper.properties.scale-$(REPLICAS).$(POD_NAME)
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zoo
spec:
  template:
    spec:
      initContainers:
      - name: init-config
        image: solsson/kafka:2.6.0-initutils-nonroot@sha256:cae9390de5380a4a1cd88976b37161ecf32fd70cde347a1db458b17ffa7743b8
      containers:
      - name: zookeeper
        image: solsson/kafka:2.6.0-zookeeper-server-start@sha256:9406e3c810254dfb2fddac951756a3f44d1036a0c476ff49e8055c8d465f5083
        args:
        - /etc/kafka/zookeeper.properties.scale-$(REPLICAS).$(POD_NAME)
