apiVersion: apps/v1
kind: Deployment
metadata:
  name: kminion
  namespace: kafka
  labels: &labels
    app: kminion
spec:
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: /metrics
    spec:
      containers:
      - name: kminion
        image: quay.io/cloudhut/kminion:v2.2.0@sha256:216c5383168b60f0797dbeb06bd6601d41ed52eb970d597492f3b1fbf944c7bd
        env:
        - name: TELEMETRY_HOST
          value: 0.0.0.0
        - name: TELEMETRY_PORT
          value: "8080"
        - name: EXPORTER_IGNORE_SYSTEM_TOPICS
          value: "true"
        - name: EXPORTER_NAMESPACE
          value: kminion
        - name: LOG_LEVEL
          value: info
        - name: KAFKA_BROKERS
          value: bootstrap:9092
        - name: KAFKA_CONSUMER_OFFSETS_TOPIC_NAME
          value: __consumer_offsets
        ports:
        - name: metrics
          containerPort: 8080
