apiVersion: apps/v1
kind: Deployment
metadata:
  name: kminion
  labels: &labels
    app: kminion
spec:
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: /metrics
    spec:
      containers:
      - name: kminion
        image: docker.io/vectorized/kminion:v2.2.1@sha256:eceaaa6cec49b94006619196e2318549099b68bc5a406d665c9929c5369f91c7
        env:
        - name: TELEMETRY_HOST
          value: 0.0.0.0
        - name: TELEMETRY_PORT
          value: "8080"
        - name: EXPORTER_IGNORE_SYSTEM_TOPICS
          value: "true"
        - name: EXPORTER_NAMESPACE
          value: kminion
        - name: LOG_LEVEL
          value: info
        - name: KAFKA_BROKERS
          value: bootstrap:9092
        - name: KAFKA_CONSUMER_OFFSETS_TOPIC_NAME
          value: __consumer_offsets
        ports:
        - name: metrics
          containerPort: 8080
